import { describe, it, expect, vi, beforeEach } from "vitest";

// `strategist` is a thin action layer over `src/lib/server/strategist`.
// The action tests verify userId propagation, and the server-helper tests
// verify the platform-column behavior (default X, filter on read, precheck
// on delete). Note: strategist does NOT itself call an LLM — the
// `@/prompts` modules and `ai` SDK are only touched from the cron route,
// not from these actions. The test still mocks `ai` defensively so any
// future refactor that pulls a generator into the action layer fails fast
// if the mock isn't configured.

const { USER_ID } = vi.hoisted(() => ({ USER_ID: "user-strategist-1" }));

vi.mock("@/lib/auth", () => ({
  requireUserId: vi.fn().mockResolvedValue(USER_ID),
}));

vi.mock("next/cache", () => ({ revalidatePath: vi.fn() }));

// Defensive mock — strategist.ts today doesn't hit the LLM, but future
// refactors must not silently start calling it from a unit test.
vi.mock("ai", () => ({
  generateText: vi.fn().mockRejectedValue(new Error("ai.generateText should not run in tests")),
  streamText: vi.fn().mockRejectedValue(new Error("ai.streamText should not run in tests")),
}));

const prismaMock = vi.hoisted(() => ({
  strategyAnalysis: {
    create: vi.fn(),
    findMany: vi.fn(),
    findFirst: vi.fn(),
    delete: vi.fn(),
  },
}));
vi.mock("@/lib/prisma", () => ({ prisma: prismaMock }));

import { revalidatePath } from "next/cache";
import {
  saveAnalysis as saveAnalysisAction,
  getAnalyses as getAnalysesAction,
  getAnalysis as getAnalysisAction,
  deleteAnalysis as deleteAnalysisAction,
} from "../strategist";

const BASE_ROW = {
  id: "sa-1",
  platform: "X",
  weekStart: new Date("2026-04-01"),
  recommendation: "text",
  createdAt: new Date("2026-04-01"),
  csvSummary: {},
  searchQueries: [],
  autoGenerated: false,
};

const BASE_CSV_SUMMARY = {
  totalPosts: 0,
  dateRange: { from: "2026-04-01", to: "2026-04-07" },
  avgImpressions: 0,
  maxImpressions: 0,
  totalNewFollows: 0,
  avgEngagementRate: 0,
  topPosts: [],
};

beforeEach(() => {
  vi.clearAllMocks();
  prismaMock.strategyAnalysis.create.mockResolvedValue(BASE_ROW);
  prismaMock.strategyAnalysis.findMany.mockResolvedValue([]);
  prismaMock.strategyAnalysis.findFirst.mockResolvedValue(null);
  prismaMock.strategyAnalysis.delete.mockResolvedValue(BASE_ROW);
});

describe("saveAnalysis (action) — userId propagation", () => {
  it("writes the authenticated userId to Prisma.create", async () => {
    await saveAnalysisAction({
      csvSummary: BASE_CSV_SUMMARY,
      searchQueries: ["q1"],
      recommendation: "rec",
      weekStart: new Date("2026-04-01"),
    });

    expect(prismaMock.strategyAnalysis.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({ userId: USER_ID }),
      })
    );
  });

  it("defaults platform to 'X' when the action caller omits it", async () => {
    await saveAnalysisAction({
      csvSummary: BASE_CSV_SUMMARY,
      searchQueries: [],
      recommendation: "rec",
      weekStart: new Date("2026-04-01"),
    });

    const data = prismaMock.strategyAnalysis.create.mock.calls[0]![0].data;
    expect(data.platform).toBe("X");
  });

  it("persists the explicit platform argument", async () => {
    await saveAnalysisAction({
      platform: "LINKEDIN",
      csvSummary: BASE_CSV_SUMMARY,
      searchQueries: [],
      recommendation: "rec",
      weekStart: new Date("2026-04-01"),
    });

    expect(prismaMock.strategyAnalysis.create.mock.calls[0]![0].data.platform).toBe("LINKEDIN");
  });

  it("invalidates the strategist page cache after a write", async () => {
    await saveAnalysisAction({
      csvSummary: BASE_CSV_SUMMARY,
      searchQueries: [],
      recommendation: "rec",
      weekStart: new Date("2026-04-01"),
    });

    expect(revalidatePath).toHaveBeenCalledWith("/strategist");
  });
});

describe("getAnalyses (action) — userId scoping + platform filter", () => {
  it("scopes findMany by userId with no platform when omitted", async () => {
    await getAnalysesAction();

    const where = prismaMock.strategyAnalysis.findMany.mock.calls[0]![0].where;
    expect(where).toEqual({ userId: USER_ID });
    // Explicitly assert `platform` key is absent — an accidental
    // `platform: undefined` would let the platform-scoped UI read stale rows.
    expect("platform" in where).toBe(false);
  });

  it("forwards the platform argument into the where clause", async () => {
    await getAnalysesAction("THREADS");

    expect(prismaMock.strategyAnalysis.findMany.mock.calls[0]![0].where).toEqual({
      userId: USER_ID,
      platform: "THREADS",
    });
  });
});

describe("getAnalysis (action) — userId-scoped single read", () => {
  it("findFirst uses (id, userId) — no cross-tenant read", async () => {
    await getAnalysisAction("sa-123");

    expect(prismaMock.strategyAnalysis.findFirst).toHaveBeenCalledWith({
      where: { id: "sa-123", userId: USER_ID },
    });
  });

  it("returns null when the row does not exist for the caller", async () => {
    prismaMock.strategyAnalysis.findFirst.mockResolvedValue(null);

    const out = await getAnalysisAction("sa-999");
    expect(out).toBeNull();
  });
});

describe("deleteAnalysis (action) — precheck before write", () => {
  it("throws Analysis not found when precheck fails, and does NOT delete", async () => {
    prismaMock.strategyAnalysis.findFirst.mockResolvedValue(null);

    await expect(deleteAnalysisAction("sa-victim")).rejects.toThrow("Analysis not found");

    // Critical: no delete on a non-existent / cross-tenant row.
    expect(prismaMock.strategyAnalysis.delete).not.toHaveBeenCalled();
  });

  it("precheck is scoped by (id, userId) before the delete fires", async () => {
    prismaMock.strategyAnalysis.findFirst.mockResolvedValue({ id: "sa-1" });

    await deleteAnalysisAction("sa-1");

    expect(prismaMock.strategyAnalysis.findFirst).toHaveBeenCalledWith({
      where: { id: "sa-1", userId: USER_ID },
    });
    expect(prismaMock.strategyAnalysis.delete).toHaveBeenCalledWith({
      where: { id: "sa-1" },
    });
    expect(revalidatePath).toHaveBeenCalledWith("/strategist");
  });
});
