import { describe, it, expect, vi, beforeEach } from "vitest";

// ADR-008 Phase 6: per-platform strategist actions.
//
// Verifies that both reads and writes carry the platform column — the
// regression we guard against is cross-platform leakage, where e.g.
// an X analysis shows up when the LinkedIn tab is asked for.

vi.mock("@/lib/auth", () => ({ requireUserId: vi.fn() }));
vi.mock("next/cache", () => ({ revalidatePath: vi.fn() }));

const prismaMock = vi.hoisted(() => ({
  strategyAnalysis: {
    create: vi.fn(),
    findMany: vi.fn(),
  },
  planProposal: {
    create: vi.fn(),
    findMany: vi.fn(),
  },
}));
vi.mock("@/lib/prisma", () => ({ prisma: prismaMock }));

import { requireUserId } from "@/lib/auth";
import { saveAnalysisInternal, getAnalysesInternal } from "../strategist";
import { savePlanProposalInternal, getAcceptedProposalsInternal } from "../plan-proposal";

const USER_ID = "user-phase6";

const baseCsvSummary = {
  totalPosts: 5,
  dateRange: { from: "2026-04-01", to: "2026-04-07" },
  avgImpressions: 100,
  maxImpressions: 500,
  totalNewFollows: 3,
  avgEngagementRate: 1.2,
  topPosts: [],
};

beforeEach(() => {
  vi.clearAllMocks();
  (requireUserId as ReturnType<typeof vi.fn>).mockResolvedValue(USER_ID);
  prismaMock.strategyAnalysis.create.mockResolvedValue({
    id: "sa-1",
    platform: "X",
    weekStart: new Date("2026-04-01"),
    recommendation: "...",
    createdAt: new Date("2026-04-01"),
    csvSummary: baseCsvSummary,
    searchQueries: [],
    autoGenerated: true,
  });
  prismaMock.strategyAnalysis.findMany.mockResolvedValue([]);
  prismaMock.planProposal.create.mockResolvedValue({
    id: "pp-1",
    platform: "LINKEDIN",
    status: "PENDING",
    proposalType: "config",
    changes: [],
    summary: "s",
    analysisId: null,
    metricsSnapshot: null,
    createdAt: new Date("2026-04-01"),
  });
  prismaMock.planProposal.findMany.mockResolvedValue([]);
});

describe("saveAnalysisInternal — platform column", () => {
  it("defaults to X when no platform is given (legacy callers)", async () => {
    await saveAnalysisInternal(USER_ID, {
      csvSummary: baseCsvSummary,
      searchQueries: [],
      recommendation: "text",
      weekStart: new Date("2026-04-01"),
    });
    const call = prismaMock.strategyAnalysis.create.mock.calls[0]![0];
    expect(call.data.platform).toBe("X");
    expect(call.data.userId).toBe(USER_ID);
  });

  it("persists the explicit platform argument", async () => {
    await saveAnalysisInternal(USER_ID, {
      platform: "LINKEDIN",
      csvSummary: baseCsvSummary,
      searchQueries: [],
      recommendation: "text",
      weekStart: new Date("2026-04-01"),
    });
    expect(prismaMock.strategyAnalysis.create.mock.calls[0]![0].data.platform).toBe("LINKEDIN");
  });
});

describe("getAnalysesInternal — platform filter", () => {
  it("omits platform from the where clause when no platform is given", async () => {
    await getAnalysesInternal(USER_ID);
    const where = prismaMock.strategyAnalysis.findMany.mock.calls[0]![0].where;
    expect(where).toEqual({ userId: USER_ID });
    // No cross-platform leakage via an accidental undefined — the
    // filter must not include `platform: undefined`.
    expect("platform" in where).toBe(false);
  });

  it("adds the platform filter when specified", async () => {
    await getAnalysesInternal(USER_ID, "THREADS");
    expect(prismaMock.strategyAnalysis.findMany.mock.calls[0]![0].where).toEqual({
      userId: USER_ID,
      platform: "THREADS",
    });
  });
});

describe("savePlanProposalInternal — platform column", () => {
  it("defaults to X when omitted", async () => {
    await savePlanProposalInternal(USER_ID, {
      changes: [],
      summary: "s",
    });
    expect(prismaMock.planProposal.create.mock.calls[0]![0].data.platform).toBe("X");
  });

  it("persists explicit platform for new LinkedIn proposals", async () => {
    await savePlanProposalInternal(USER_ID, {
      platform: "LINKEDIN",
      changes: [],
      summary: "s",
    });
    expect(prismaMock.planProposal.create.mock.calls[0]![0].data.platform).toBe("LINKEDIN");
  });
});

describe("getAcceptedProposalsInternal — platform filter", () => {
  it("returns all platforms when no filter is given", async () => {
    await getAcceptedProposalsInternal(USER_ID, 30);
    const where = prismaMock.planProposal.findMany.mock.calls[0]![0].where;
    expect(where.userId).toBe(USER_ID);
    expect(where.status).toBe("ACCEPTED");
    expect("platform" in where).toBe(false);
  });

  it("filters by platform when specified — guards against cross-platform leakage", async () => {
    await getAcceptedProposalsInternal(USER_ID, 30, "THREADS");
    const where = prismaMock.planProposal.findMany.mock.calls[0]![0].where;
    expect(where).toMatchObject({ userId: USER_ID, status: "ACCEPTED", platform: "THREADS" });
  });

  it("uses a correct N-day-ago cutoff", async () => {
    const before = Date.now();
    await getAcceptedProposalsInternal(USER_ID, 14, "X");
    const after = Date.now();
    const where = prismaMock.planProposal.findMany.mock.calls[0]![0].where;
    const cutoff = (where.reviewedAt.gte as Date).getTime();
    // Cutoff should be ~14 days before "now" — we allow a generous
    // tolerance since the test doesn't mock Date.
    const fourteenDays = 14 * 24 * 60 * 60 * 1000;
    expect(cutoff).toBeGreaterThanOrEqual(before - fourteenDays - 1000);
    expect(cutoff).toBeLessThanOrEqual(after - fourteenDays + 1000);
  });
});
