import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/prisma";
import type { CsvSummary, StrategyAnalysisItem } from "@/lib/types";
import type { Platform } from "@/generated/prisma";

// ADR-008 Phase 6: analyses are scoped per (userId × platform). Reads
// ALWAYS filter by platform; a user may have up to 3 analyses running
// independently, and we never want the X analysis to leak into the
// LinkedIn view.

function mapRow(row: {
  id: string;
  platform: Platform;
  weekStart: Date;
  recommendation: string;
  createdAt: Date;
  csvSummary: unknown;
  searchQueries: string[];
  autoGenerated: boolean;
}): StrategyAnalysisItem {
  return {
    id: row.id,
    platform: row.platform,
    weekStart: row.weekStart,
    recommendation: row.recommendation,
    createdAt: row.createdAt,
    csvSummary: row.csvSummary as unknown as CsvSummary,
    searchQueries: row.searchQueries,
    autoGenerated: row.autoGenerated,
  };
}

export async function saveAnalysis(
  userId: string,
  data: {
    platform?: Platform;
    csvSummary: CsvSummary;
    searchQueries: string[];
    recommendation: string;
    weekStart: Date;
    autoGenerated?: boolean;
  }
): Promise<StrategyAnalysisItem> {
  const row = await prisma.strategyAnalysis.create({
    data: {
      userId,
      platform: data.platform ?? "X",
      csvSummary: data.csvSummary as object,
      searchQueries: data.searchQueries,
      recommendation: data.recommendation,
      weekStart: data.weekStart,
      autoGenerated: data.autoGenerated ?? false,
    },
  });

  revalidatePath("/strategist");

  return mapRow(row);
}

export async function getAnalyses(
  userId: string,
  platform?: Platform
): Promise<StrategyAnalysisItem[]> {
  const rows = await prisma.strategyAnalysis.findMany({
    where: platform ? { userId, platform } : { userId },
    orderBy: { createdAt: "desc" },
    select: {
      id: true,
      platform: true,
      weekStart: true,
      recommendation: true,
      createdAt: true,
      csvSummary: true,
      searchQueries: true,
      autoGenerated: true,
    },
  });

  return rows.map(mapRow);
}

export async function getAnalysis(
  userId: string,
  id: string
): Promise<StrategyAnalysisItem | null> {
  const row = await prisma.strategyAnalysis.findFirst({ where: { id, userId } });
  if (!row) return null;
  return mapRow(row);
}

export async function deleteAnalysis(userId: string, id: string): Promise<void> {
  const row = await prisma.strategyAnalysis.findFirst({ where: { id, userId } });
  if (!row) throw new Error("Analysis not found");
  await prisma.strategyAnalysis.delete({ where: { id } });
  revalidatePath("/strategist");
}
