-- CreateEnum
CREATE TYPE "XPostType" AS ENUM ('POST', 'REPLY');

-- CreateEnum
CREATE TYPE "DataSource" AS ENUM ('CSV', 'API');

-- CreateEnum
CREATE TYPE "ProposalStatus" AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED');

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "SlotType" ADD VALUE 'THREAD';
ALTER TYPE "SlotType" ADD VALUE 'ARTICLE';

-- AlterTable
ALTER TABLE "Conversation" ADD COLUMN     "lastActivityAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "pinned" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "ScheduledSlot" ADD COLUMN     "postedAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "StrategyConfig" ADD COLUMN     "scheduleConfig" JSONB,
ADD COLUMN     "targetDate" TIMESTAMP(3),
ADD COLUMN     "targetFollowers" INTEGER,
ALTER COLUMN "updatedAt" DROP DEFAULT;

-- CreateTable
CREATE TABLE "XPost" (
    "id" TEXT NOT NULL,
    "postId" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "text" TEXT NOT NULL,
    "postLink" TEXT,
    "postType" "XPostType" NOT NULL,
    "impressions" INTEGER NOT NULL DEFAULT 0,
    "likes" INTEGER NOT NULL DEFAULT 0,
    "engagements" INTEGER NOT NULL DEFAULT 0,
    "bookmarks" INTEGER NOT NULL DEFAULT 0,
    "replies" INTEGER NOT NULL DEFAULT 0,
    "reposts" INTEGER NOT NULL DEFAULT 0,
    "quoteCount" INTEGER NOT NULL DEFAULT 0,
    "urlClicks" INTEGER NOT NULL DEFAULT 0,
    "profileVisits" INTEGER NOT NULL DEFAULT 0,
    "newFollowers" INTEGER NOT NULL DEFAULT 0,
    "detailExpands" INTEGER NOT NULL DEFAULT 0,
    "dataSource" "DataSource" NOT NULL DEFAULT 'CSV',
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "XPost_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DailyAccountStats" (
    "id" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "impressions" INTEGER NOT NULL DEFAULT 0,
    "likes" INTEGER NOT NULL DEFAULT 0,
    "engagements" INTEGER NOT NULL DEFAULT 0,
    "bookmarks" INTEGER NOT NULL DEFAULT 0,
    "shares" INTEGER NOT NULL DEFAULT 0,
    "newFollows" INTEGER NOT NULL DEFAULT 0,
    "unfollows" INTEGER NOT NULL DEFAULT 0,
    "replies" INTEGER NOT NULL DEFAULT 0,
    "reposts" INTEGER NOT NULL DEFAULT 0,
    "profileVisits" INTEGER NOT NULL DEFAULT 0,
    "createPost" INTEGER NOT NULL DEFAULT 0,
    "videoViews" INTEGER NOT NULL DEFAULT 0,
    "mediaViews" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "DailyAccountStats_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "StrategyAnalysis" (
    "id" TEXT NOT NULL,
    "csvSummary" JSONB NOT NULL,
    "searchQueries" TEXT[],
    "recommendation" TEXT NOT NULL,
    "weekStart" TIMESTAMP(3) NOT NULL,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "StrategyAnalysis_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ResearchNote" (
    "id" TEXT NOT NULL,
    "topic" TEXT NOT NULL,
    "summary" TEXT NOT NULL,
    "sources" JSONB NOT NULL,
    "queries" TEXT[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ResearchNote_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DailyInsight" (
    "id" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "insights" JSONB NOT NULL,
    "context" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "DailyInsight_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FollowersSnapshot" (
    "id" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "followersCount" INTEGER NOT NULL,
    "followingCount" INTEGER NOT NULL,
    "deltaFollowers" INTEGER NOT NULL DEFAULT 0,
    "deltaFollowing" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "FollowersSnapshot_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TrendSnapshot" (
    "id" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "trendName" TEXT NOT NULL,
    "postCount" INTEGER NOT NULL DEFAULT 0,
    "category" TEXT,
    "trendingSince" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fetchHour" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "TrendSnapshot_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PostEngagementSnapshot" (
    "id" TEXT NOT NULL,
    "postId" TEXT NOT NULL,
    "snapshotDate" TIMESTAMP(3) NOT NULL,
    "impressions" INTEGER NOT NULL DEFAULT 0,
    "likes" INTEGER NOT NULL DEFAULT 0,
    "engagements" INTEGER NOT NULL DEFAULT 0,
    "bookmarks" INTEGER NOT NULL DEFAULT 0,
    "replies" INTEGER NOT NULL DEFAULT 0,
    "reposts" INTEGER NOT NULL DEFAULT 0,
    "quoteCount" INTEGER NOT NULL DEFAULT 0,
    "profileVisits" INTEGER NOT NULL DEFAULT 0,
    "urlClicks" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PostEngagementSnapshot_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PlanProposal" (
    "id" TEXT NOT NULL,
    "status" "ProposalStatus" NOT NULL DEFAULT 'PENDING',
    "proposalType" TEXT NOT NULL DEFAULT 'config',
    "changes" JSONB NOT NULL,
    "summary" TEXT NOT NULL,
    "analysisId" TEXT,
    "metricsSnapshot" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reviewedAt" TIMESTAMP(3),

    CONSTRAINT "PlanProposal_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "XPost_postId_key" ON "XPost"("postId");

-- CreateIndex
CREATE UNIQUE INDEX "DailyAccountStats_date_key" ON "DailyAccountStats"("date");

-- CreateIndex
CREATE UNIQUE INDEX "DailyInsight_date_key" ON "DailyInsight"("date");

-- CreateIndex
CREATE UNIQUE INDEX "FollowersSnapshot_date_key" ON "FollowersSnapshot"("date");

-- CreateIndex
CREATE INDEX "TrendSnapshot_date_fetchHour_idx" ON "TrendSnapshot"("date", "fetchHour");

-- CreateIndex
CREATE INDEX "PostEngagementSnapshot_postId_idx" ON "PostEngagementSnapshot"("postId");

-- CreateIndex
CREATE UNIQUE INDEX "PostEngagementSnapshot_postId_snapshotDate_key" ON "PostEngagementSnapshot"("postId", "snapshotDate");
