"use server";

import { requireUserId } from "@/lib/auth";
import type { CsvSummary, StrategyAnalysisItem } from "@/lib/types";
import type { Platform } from "@/generated/prisma";
import {
  saveAnalysis as _saveAnalysis,
  getAnalyses as _getAnalyses,
  getAnalysis as _getAnalysis,
  deleteAnalysis as _deleteAnalysis,
} from "@/lib/server/strategist";

export async function saveAnalysis(data: {
  platform?: Platform;
  csvSummary: CsvSummary;
  searchQueries: string[];
  recommendation: string;
  weekStart: Date;
  autoGenerated?: boolean;
}): Promise<StrategyAnalysisItem> {
  const userId = await requireUserId();
  return _saveAnalysis(userId, data);
}

export async function getAnalyses(platform?: Platform): Promise<StrategyAnalysisItem[]> {
  const userId = await requireUserId();
  return _getAnalyses(userId, platform);
}

export async function getAnalysis(id: string): Promise<StrategyAnalysisItem | null> {
  const userId = await requireUserId();
  return _getAnalysis(userId, id);
}

export async function deleteAnalysis(id: string): Promise<void> {
  const userId = await requireUserId();
  return _deleteAnalysis(userId, id);
}
